---
title: "Quiz Night 2026"
author: "Leanne Darnbrough, Thomas Van Hoey, en Anneleen Masschelein"
format:
  revealjs:
    incremental: true
    logo: quiz_europese_taalkunde/logo.png
    # footer: ""
    transition: fade
    css: presentation/style.css
include-after-body: presentation/fragmentPlay.html
---

::: {.text-center .v-center-container}

<div style="font-size: 5vh;">

In deze quiz slaan de docenten van de algemene vakken in het eerste jaar Taal- en Letterkunde aan de KU Leuven de handen in elkaar!  
Welkom!

</div>

:::

::: {.notes}
Uitleg over de avond.
:::

## Strijdende teams vanavond

NOG TE DOEN

- Pipopapipo
- Taylor Quist
- Goethe verliezers
- Don Quizote
- De Athosbergbestormers
- Adulescentes capientes
- De sint-dimpnagirls



## De regels

1. Geen gsm's!
1. Personen: achternaam volstaat -- als je de voornaam geeft, moet die correct zijn
1. Kleinste punteenheid = half puntje
<!-- 2. Ben je het niet eens met een antwoord? Zeuren kan tijdens de pauze -->
<!-- 3. De jury beslist of ze naar jullie gezeur zal luisteren -->
<!-- 4. De dorstigen zullen gelaafd worden! -->
5. Geniet van de avond!

::: {.notes}
Eerst een paar regels

1. Geen gsm's!
1. Personen: achternaam volstaat -- als je de voornaam geeft, moet die correct zijn
1. Kleinste punteenheid = half puntje
<!-- 2. Ben je het niet eens met een antwoord? Zeuren kan tijdens de pauze -->
<!-- 3. De jury beslist of ze naar jullie gezeur zal luisteren -->
<!-- 4. De dorstigen zullen gelaafd worden! Je kan je bestelling doorgeven op een blaadje en de studenten zullen rondkomen. Betalen kan via payconic. -->
5. Geniet van de avond!

:::

## Voor we beginnen...

Met dank aan onze verbeteraars en juryleden 🫰🏻️

Onthoud, *de pen is machtiger dan het zwaard*.

Graag een applausje voor hen!


## Rondes


::::: {.columns}

:::: {.column width="50%"}

1. Mémé leest een boek
2. 600 kaarsjes voor de KU Leuven
3. ALW 1 - Electric Boogaloo - Tokyo Drift
4. Fun with friends and phonemes

:::  {.fragment}

Tafelronde 1 <br> 5. Europese Sudoku


:::

::::

:::: {.column width="50%"}

PAUZE

6. ATW uit de oude doos
7. Oulipo S club 7 
8. Music Maestro
9. Van vers tot verf

:::  {.fragment}

Tafelronde 2 <br> 10. Cryptogrammen van den ALWi

:::

::::

:::::



----

::: {.text-center .v-center-container}

<div style="text-align: center; font-size: 10vw;">

Veel succes!
</div>

:::